let apps=[],view='home',cat='all';const $=s=>document.querySelector(s),grid=$('#grid'),search=$('#search');const favs=()=>JSON.parse(localStorage.getItem('orbis-favs')||'[]');const own=()=>JSON.parse(localStorage.getItem('orbis-files')||'[]');const queue=()=>JSON.parse(sessionStorage.getItem('orbis-queue')||'[]');const icon=a=>({Jogos:'🎮',Emuladores:'🕹',Utilitários:'🛠',Temas:'🎨',Desenvolvimento:'⌘'}[a.category]||'📦');
function render(){let list=[...apps];if(view==='favorites')list=list.filter(a=>favs().includes(a.id));if(view==='new')list.sort((a,b)=>(b.added||'').localeCompare(a.added||''));if(view==='popular')list.sort((a,b)=>(b.downloads||0)-(a.downloads||0));if(cat!=='all')list=list.filter(a=>a.category===cat);let q=search.value.toLowerCase();list=list.filter(a=>(a.name+' '+a.description+' '+a.developer).toLowerCase().includes(q));grid.innerHTML='';list.forEach(a=>{let c=document.createElement('article');c.className='card';c.innerHTML='<div class="cover">'+icon(a)+'</div><button class="fav '+(favs().includes(a.id)?'saved':'')+'" data-fav="'+a.id+'">★</button><div class="cardbody"><div class="meta"><span>'+a.category+'</span><span>v'+a.version+'</span></div><h3>'+esc(a.name)+'</h3><p>'+esc(a.description)+'</p><div class="cardactions"><button data-info="'+a.id+'">Detalhes</button><button class="get" data-get="'+a.id+'">Baixar</button></div></div>';grid.append(c)});$('#count').textContent=list.length+' itens';bind()}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function safe(u){try{let x=new URL(u);return ['http:','https:'].includes(x.protocol)?x.href:'#'}catch{return'#'}}
function bind(){document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{let f=favs(),id=b.dataset.fav;f=f.includes(id)?f.filter(x=>x!==id):[...f,id];localStorage.setItem('orbis-favs',JSON.stringify(f));render()});document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>details(apps.find(a=>a.id===b.dataset.info)));document.querySelectorAll('[data-get]').forEach(b=>b.onclick=()=>download(apps.find(a=>a.id===b.dataset.get)))}
function details(a){$('#detailBody').innerHTML='<div class="detailhero"><div class="detailicon">'+icon(a)+'</div><div><span class="pill">'+esc(a.category)+'</span><h2>'+esc(a.name)+'</h2><p class="muted">'+esc(a.description)+'</p></div></div><div class="facts"><div class="fact"><b>VERSÃO</b>'+esc(a.version)+'</div><div class="fact"><b>TAMANHO</b>'+esc(a.size)+'</div><div class="fact"><b>DESENVOLVEDOR</b>'+esc(a.developer)+'</div><div class="fact"><b>FORMATO</b>'+esc(a.type)+'</div><div class="fact"><b>FIRMWARE</b>'+esc(a.firmware)+'</div><div class="fact"><b>DOWNLOADS</b>'+Number(a.downloads||0).toLocaleString()+'</div></div><div class="shots"><div class="shot">Screenshot / preview</div><div class="shot">Screenshot / preview</div></div><p><b>SHA-256</b></p><p class="hash">'+esc(a.sha256||'Não informado')+'</p><button class="primary" id="detailGet">⇩ Baixar '+esc(a.type)+'</button>';$('#details').classList.remove('hidden');$('#detailGet').onclick=()=>download(a)}
function download(a){let u=safe(a.url);if(u==='#')return alert('URL de download não configurada.');let q=queue();q.unshift({name:a.name,status:'Iniciado',time:new Date().toLocaleTimeString()});sessionStorage.setItem('orbis-queue',JSON.stringify(q));renderQueue();window.open(u,'_blank')}
function renderQueue(){$('#queue').innerHTML=queue().map(x=>'<div class="queueitem"><b>'+esc(x.name)+'</b><span class="status">'+esc(x.status)+'</span><span>'+esc(x.time)+'</span></div>').join('')||'<p class="muted">Nenhum download iniciado nesta sessão.</p>'}
function renderOwn(){$('#myFiles').innerHTML=own().map((a,i)=>'<article class="card"><div class="cover">📦</div><div class="cardbody"><div class="meta"><span>'+esc(a.type)+'</span><span>'+esc(a.version||'—')+'</span></div><h3>'+esc(a.name)+'</h3><p>'+esc(a.description||'Arquivo próprio')+'</p><div class="cardactions"><button class="get" data-own="'+i+'">Baixar</button></div></div></article>').join('')||'<p class="muted">Você ainda não adicionou arquivos.</p>';document.querySelectorAll('[data-own]').forEach(b=>b.onclick=()=>window.open(safe(own()[+b.dataset.own].url),'_blank'))}
fetch('apps.json').then(r=>r.json()).then(x=>{apps=x;render()}).catch(()=>render());search.oninput=render;$('#explore').onclick=()=>grid.scrollIntoView({behavior:'smooth'});$('#uploadBtn').onclick=$('#addFile').onclick=()=>$('#upload').classList.remove('hidden');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));
$('#cats').onclick=e=>{let b=e.target.closest('button');if(!b)return;document.querySelectorAll('#cats button').forEach(x=>x.classList.remove('on'));b.classList.add('on');cat=b.dataset.cat;render()};
$('#nav').onclick=e=>{let b=e.target.closest('button');if(!b)return;document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;$('#filesPanel').classList.toggle('hidden',view!=='files');$('#downloadsPanel').classList.toggle('hidden',view!=='downloads');grid.parentElement.classList.toggle('hidden',view==='files'||view==='downloads');$('.hero').classList.toggle('hidden',view==='files'||view==='downloads');$('.cats').classList.toggle('hidden',view==='files'||view==='downloads');if(view==='files')renderOwn();if(view==='downloads')renderQueue();if(!['files','downloads'].includes(view))render()};
$('#fileForm').onsubmit=e=>{e.preventDefault();let a={name:$('#fname').value,url:$('#furl').value,type:$('#ftype').value,version:$('#fversion').value,description:$('#fdesc').value};let x=own();x.push(a);localStorage.setItem('orbis-files',JSON.stringify(x));e.target.reset();$('#upload').classList.add('hidden');renderOwn()};