var apps=[],view='home',cat='all',musicPlaying=false;function qs(s){return document.querySelector(s)}function qsa(s){return document.querySelectorAll(s)}function storeGet(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}}function favs(){return storeGet('orbis-favs',[])}function own(){return storeGet('orbis-files',[])}function esc(s){s=String(s||'');return s.replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}function icon(a){var x={Jogos:'🎮',Emuladores:'🕹',Utilitários:'🛠',Temas:'🎨',Desenvolvimento:'⌘'};return x[a.category]||'📦'}function safe(u){var a=document.createElement('a');a.href=u;return a.protocol==='http:'||a.protocol==='https:'?a.href:'#'}
function render(){var list=apps.slice(),f=favs(),term=qs('#search').value.toLowerCase(),i,a,c;if(view==='favorites')list=list.filter(function(x){return f.indexOf(x.id)>-1});if(view==='new')list.sort(function(a,b){return String(b.added).localeCompare(String(a.added))});if(view==='popular')list.sort(function(a,b){return (b.downloads||0)-(a.downloads||0)});if(cat!=='all')list=list.filter(function(x){return x.category===cat});list=list.filter(function(x){return (x.name+' '+x.description+' '+x.developer).toLowerCase().indexOf(term)>-1});qs('#grid').innerHTML='';for(i=0;i<list.length;i++){a=list[i];c=document.createElement('article');c.className='card';c.setAttribute('tabindex','0');c.setAttribute('data-appid',a.id);c.innerHTML='<div class="cover">'+icon(a)+'</div><button class="fav '+(f.indexOf(a.id)>-1?'saved':'')+'" data-fav="'+a.id+'">★</button><div class="cardbody"><div class="meta"><span>'+esc(a.category)+'</span><span>v'+esc(a.version)+'</span></div><h3>'+esc(a.name)+'</h3><p>'+esc(a.description)+'</p><div class="actions"><button data-info="'+a.id+'">Detalhes</button><button class="get" data-get="'+a.id+'">Baixar</button></div></div>';qs('#grid').appendChild(c)}qs('#count').innerHTML=list.length+' itens';bindCards();bindHero();if(list.length)updateHero(list[0])}
function updateHero(a){if(!a)return;var t=qs('#heroTitle'),d=qs('#heroDesc');if(t)t.innerHTML=esc(a.name);if(d)d.innerHTML=esc(a.description||a.category)}
function bindHero(){var cards=qsa('.card[data-appid]'),i;for(i=0;i<cards.length;i++){cards[i].onfocus=cards[i].onmouseenter=function(){var a=findApp(this.getAttribute('data-appid'));updateHero(a)}}}
function findApp(id){for(var i=0;i<apps.length;i++)if(apps[i].id===id)return apps[i];return null}function bindCards(){var i,x=qsa('[data-fav]');for(i=0;i<x.length;i++)x[i].onclick=function(){var f=favs(),id=this.getAttribute('data-fav'),p=f.indexOf(id);if(p>-1)f.splice(p,1);else f.push(id);localStorage.setItem('orbis-favs',JSON.stringify(f));render()};x=qsa('[data-info]');for(i=0;i<x.length;i++)x[i].onclick=function(){details(findApp(this.getAttribute('data-info')))};x=qsa('[data-get]');for(i=0;i<x.length;i++)x[i].onclick=function(){download(findApp(this.getAttribute('data-get')))}}
function details(a){if(!a)return;qs('#detailBody').innerHTML='<h2>'+icon(a)+' '+esc(a.name)+'</h2><p class="muted">'+esc(a.description)+'</p><div class="facts"><div class="fact"><b>VERSÃO</b>'+esc(a.version)+'</div><div class="fact"><b>TAMANHO</b>'+esc(a.size)+'</div><div class="fact"><b>DEV</b>'+esc(a.developer)+'</div><div class="fact"><b>FORMATO</b>'+esc(a.type)+'</div><div class="fact"><b>FIRMWARE</b>'+esc(a.firmware)+'</div><div class="fact"><b>DOWNLOADS</b>'+esc(a.downloads)+'</div></div><p><b>SHA-256</b></p><p class="hash">'+esc(a.sha256||'Não informado')+'</p><button id="detailGet" class="blue">Baixar '+esc(a.type)+'</button>';qs('#details').className='modal';qs('#detailGet').onclick=function(){download(a)}}
function download(a){if(!a)return;var u=safe(a.url);if(u==='#'){alert('Este item é demonstrativo e ainda não possui um link real.');return}var q=storeGet('orbis-queue',[]);q.unshift({name:a.name,status:'Iniciado'});localStorage.setItem('orbis-queue',JSON.stringify(q));renderQueue();notify('Download iniciado: '+a.name);window.location.href=u}
function renderQueue(){var q=storeGet('orbis-queue',[]),h='',i;for(i=0;i<q.length;i++)h+='<div class="queueitem"><b>'+esc(q[i].name)+'</b><span>'+esc(q[i].status)+'</span></div>';qs('#queue').innerHTML=h||'<p class="muted">Nenhum download iniciado.</p>'}
function renderOwn(){var x=own(),h='',i;for(i=0;i<x.length;i++)h+='<article class="card"><div class="cover">📦</div><div class="cardbody"><div class="meta"><span>'+esc(x[i].type)+'</span><span>'+esc(x[i].version||'—')+'</span></div><h3>'+esc(x[i].name)+'</h3><p>'+esc(x[i].description||'Arquivo próprio')+'</p><div class="actions"><button class="get" data-own="'+i+'">Baixar</button></div></div></article>';qs('#myFiles').innerHTML=h||'<p class="muted">Nenhum arquivo adicionado.</p>';var b=qsa('[data-own]');for(i=0;i<b.length;i++)b[i].onclick=function(){var a=own()[parseInt(this.getAttribute('data-own'),10)];window.location.href=safe(a.url)}}
function notify(t){var x=qs('#toast');if(!x)return;x.innerHTML=esc(t);x.className='toast';setTimeout(function(){x.className='toast hidden'},2200)}
function loadProfile(){var p=storeGet('orbis-profile',{name:'PLAYER'}),n=p.name||'PLAYER',a=n.charAt(0).toUpperCase();qs('#profileName').innerHTML=esc(n);qs('#avatar').innerHTML=esc(a);qs('#avatarBig').innerHTML=esc(a);qs('#pname').value=n}
function setupProfile(){loadProfile();qs('#profileBtn').onclick=function(){qs('#profileModal').className='modal';qs('#pname').focus()};qs('#profileForm').onsubmit=function(e){e.preventDefault();var n=qs('#pname').value||'PLAYER';localStorage.setItem('orbis-profile',JSON.stringify({name:n}));loadProfile();qs('#profileModal').className='modal hidden';notify('Perfil salvo');return false}}
function setupFeatured(){if(!apps.length)return;var a=apps[0],best=apps[0];for(var i=1;i<apps.length;i++)if((apps[i].downloads||0)>(best.downloads||0))best=apps[i];a=best;qs('#featuredName').innerHTML=esc(a.name);qs('#featuredText').innerHTML=esc(a.description||a.category);qs('#featuredOpen').onclick=function(){details(a)}}
function hideSplash(){var s=qs('#splash');if(s)s.className='splash hidden'}
function setView(v){view=v;qs('#catalog').className=(v==='files'||v==='downloads')?'hidden':'';qs('#filesPanel').className=v==='files'?'':'hidden';qs('#downloadsPanel').className=v==='downloads'?'':'hidden';if(v==='files')renderOwn();else if(v==='downloads')renderQueue();else render()}
function updateClock(){var d=new Date(),h=d.getHours(),m=d.getMinutes();qs('#clock').innerHTML=(h<10?'0':'')+h+':'+(m<10?'0':'')+m}
function closeTopModal(){if(qs('#details').className.indexOf('hidden')<0){qs('#details').className='modal hidden';return true}if(qs('#upload').className.indexOf('hidden')<0){qs('#upload').className='modal hidden';return true}if(qs('#profileModal').className.indexOf('hidden')<0){qs('#profileModal').className='modal hidden';return true}return false}
function focusCard(dir){var cards=qsa('#grid .card'),active=document.activeElement,i=-1;if(!cards.length)return;for(var n=0;n<cards.length;n++)if(cards[n]===active)i=n;if(i<0)i=0;else i=(i+dir+cards.length)%cards.length;cards[i].focus();try{cards[i].scrollIntoView({block:'nearest',inline:'center'})}catch(e){cards[i].scrollIntoView(false)}}
function controllerKeys(e){var k=e.keyCode||e.which;if(k===27||k===8){if(closeTopModal()){e.preventDefault();return}}if(qs('#details').className.indexOf('hidden')<0||qs('#upload').className.indexOf('hidden')<0)return;if(k===37){focusCard(-1);e.preventDefault()}else if(k===39){focusCard(1);e.preventDefault()}else if(k===13){var el=document.activeElement;if(el&&el.className.indexOf('card')>-1){details(findApp(el.getAttribute('data-appid')));e.preventDefault()}}else if(k===38||k===40){var tabs=qsa('#nav button'),cur=document.activeElement,p=-1;for(var z=0;z<tabs.length;z++)if(tabs[z]===cur)p=z;if(k===40&&p>-1){var cards=qsa('#grid .card');if(cards.length)cards[0].focus();e.preventDefault()}else if(k===38&&cur&&cur.className.indexOf('card')>-1){var on=qs('#nav .active');if(on)on.focus();e.preventDefault()}}}
window.onload=function(){setupProfile();var sp=qs('#splash');if(sp){sp.onclick=hideSplash;sp.onkeydown=hideSplash;sp.setAttribute('tabindex','0');sp.focus()}document.addEventListener('keydown',function(e){if(qs('#splash')&&qs('#splash').className.indexOf('hidden')<0&&(e.keyCode===13||e.keyCode===88)){hideSplash();e.preventDefault()}},false);updateClock();setInterval(updateClock,30000);document.addEventListener('keydown',controllerKeys,false);var i,b=qsa('#nav button');for(i=0;i<b.length;i++)b[i].onclick=function(){var j,all=qsa('#nav button');for(j=0;j<all.length;j++)all[j].className='';this.className='active';setView(this.getAttribute('data-view'))};b=qsa('#cats button');for(i=0;i<b.length;i++)b[i].onclick=function(){var j,all=qsa('#cats button');for(j=0;j<all.length;j++)all[j].className='';this.className='on';cat=this.getAttribute('data-cat');render()};qs('#search').onkeyup=render;qs('#addFile').onclick=function(){qs('#upload').className='modal'};b=qsa('[data-close]');for(i=0;i<b.length;i++)b[i].onclick=function(){qs('#'+this.getAttribute('data-close')).className='modal hidden'};qs('#fileForm').onsubmit=function(e){e.preventDefault();var x=own();x.push({name:qs('#fname').value,url:qs('#furl').value,type:qs('#ftype').value,version:qs('#fversion').value,description:qs('#fdesc').value});localStorage.setItem('orbis-files',JSON.stringify(x));this.reset();qs('#upload').className='modal hidden';renderOwn();return false};fetch('apps.json').then(function(r){return r.json()}).then(function(x){apps=x;render();setupFeatured()}).catch(function(){render()});setupMusic()}
var musicStarted=false,currentTrack=0,currentSource=0;
var tracks=[
 {name:'♫ FIGHT! — Aests',start:24,sources:['fight-ps4.m4a','fight-ps4.mp3']},
 {name:'♫ ACENDAOFAROL — Hoodtrap version',start:0,sources:['acendaofarol-ps4.m4a','acendaofarol-ps4.mp3']}
];
function setMusicState(t){var s=qs('#musicState');if(s)s.innerHTML=t}
function sourceLabel(){return currentSource===0?'M4A/AAC':'MP3'}
function loadTrack(n,source){var a=qs('#storeAudio');currentTrack=n;currentSource=source||0;musicStarted=false;qs('#trackName').innerHTML=tracks[n].name;setMusicState('carregando '+sourceLabel()+'...');a.src=tracks[n].sources[currentSource]+'?v=5';a.load()}
function seekAndPlay(){var a=qs('#storeAudio');if(!a)return;try{if(a.readyState>0)a.currentTime=tracks[currentTrack].start}catch(e){};try{var p=a.play();if(p&&p.then){p.then(function(){musicStarted=true;setMusicState('● tocando '+sourceLabel())}).catch(function(e){musicStarted=false;if(e&&e.name==='NotSupportedError'&&currentSource===0){setMusicState('AAC não suportado; tentando MP3...');loadTrack(currentTrack,1)}else setMusicState('BLOQUEADO '+sourceLabel()+': '+(e.name||'play'))})}}catch(e){if(currentSource===0)loadTrack(currentTrack,1);else setMusicState('ERRO '+sourceLabel()+': '+e.message)}}
function unlockMusic(){var a=qs('#storeAudio');if(!a)return;a.muted=false;a.volume=1;if(a.paused||!musicStarted)seekAndPlay()}
function setupMusic(){var a=qs('#storeAudio');if(!a)return;a.muted=false;a.volume=1;a.onloadedmetadata=function(){try{a.currentTime=tracks[currentTrack].start}catch(e){};seekAndPlay()};a.oncanplay=function(){if(!musicStarted)seekAndPlay()};a.onplaying=function(){musicStarted=true;setMusicState('● tocando '+sourceLabel())};a.onended=function(){loadTrack(currentTrack===0?1:0,0)};a.onerror=function(){musicStarted=false;if(currentSource===0){setMusicState('AAC falhou; tentando MP3...');loadTrack(currentTrack,1)}else setMusicState('formato não suportado pelo navegador')};document.addEventListener('mousedown',unlockMusic,false);document.addEventListener('click',unlockMusic,false);document.addEventListener('touchstart',unlockMusic,false);document.addEventListener('keydown',unlockMusic,false);loadTrack(0,0)}