#!/usr/bin/env python3
"""Read the reviewed Archive policy and generate or check its native header."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import sys
import tempfile


MAX_POLICY_BYTES = 64 * 1024
MAX_COLLECTIONS = 128
MAX_CDN_HOSTS = 128
COLLECTION_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}")
HOST_LABEL_RE = re.compile(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?")


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate Archive policy key: {key}")
        result[key] = value
    return result


def checked_list(value, name: str, maximum: int, validator) -> tuple[str, ...]:
    if not isinstance(value, list) or not 1 <= len(value) <= maximum:
        raise ValueError(f"{name} must contain from 1 through {maximum} reviewed strings")
    seen = set()
    for item in value:
        if not isinstance(item, str) or not validator(item):
            raise ValueError(f"{name} contains an invalid reviewed string")
        if item in seen:
            raise ValueError(f"{name} contains a duplicate reviewed string")
        seen.add(item)
    return tuple(value)


def valid_collection(value: str) -> bool:
    return bool(COLLECTION_RE.fullmatch(value)) and ".." not in value


def valid_cdn_host(value: str) -> bool:
    return (len(value) <= 253 and value.endswith(".archive.org")
            and all(HOST_LABEL_RE.fullmatch(label) for label in value.split(".")))


def load_archive_policy(path: Path) -> dict:
    """Read bounded, trusted repository data; never discover or expand hosts."""
    with Path(path).open("rb") as stream:
        raw = stream.read(MAX_POLICY_BYTES + 1)
    if len(raw) > MAX_POLICY_BYTES:
        raise ValueError("Archive policy exceeds the 64 KiB read limit")
    policy = json.loads(raw.decode("utf-8", errors="strict"), object_pairs_hook=unique_object)
    if (not isinstance(policy, dict) or set(policy) != {"schema_version", "collections", "cdn_hosts"}
            or type(policy.get("schema_version")) is not int or policy["schema_version"] != 1):
        raise ValueError("Archive policy must contain exactly schema_version 1, collections and cdn_hosts")
    return {
        "schema_version": 1,
        "collections": checked_list(policy["collections"], "collections", MAX_COLLECTIONS, valid_collection),
        "cdn_hosts": checked_list(policy["cdn_hosts"], "cdn_hosts", MAX_CDN_HOSTS, valid_cdn_host),
    }


def generate_archive_header(policy: dict) -> str:
    lines = [
        "// Generated by native/scripts/archive_policy.py; do not edit.",
        "// Exact reviewed collections and hosts come from native/archive_sources.json.",
        "#ifndef PEPPY_ARCHIVE_SOURCES_H",
        "#define PEPPY_ARCHIVE_SOURCES_H",
        "",
        "#include <stddef.h>",
        "",
        "namespace peppyArchiveSources {",
        "static const char* const COLLECTIONS[] = {",
    ]
    lines.extend(f"    {json.dumps(item)}," for item in policy["collections"])
    lines.extend([
        "};",
        "static const size_t COLLECTION_COUNT = sizeof(COLLECTIONS) / sizeof(COLLECTIONS[0]);",
        "static const char* const CDN_HOSTS[] = {",
    ])
    lines.extend(f"    {json.dumps(host)}," for host in policy["cdn_hosts"])
    lines.extend([
        "};",
        "static const size_t CDN_HOST_COUNT = sizeof(CDN_HOSTS) / sizeof(CDN_HOSTS[0]);",
        "",
        "namespace detail {",
        "inline char lower(char c) { return c >= 'A' && c <= 'Z' ? char(c + ('a' - 'A')) : c; }",
        "inline bool matches(const char* value, size_t length, const char* expected, bool dns) {",
        "    if (!value) return false;",
        "    for (size_t i = 0; i < length; ++i) {",
        "        if (!expected[i] || (dns ? lower(value[i]) : value[i]) != expected[i]) return false;",
        "    }",
        "    return !expected[length];",
        "}",
        "} // namespace detail",
        "",
        "inline bool approvedCollection(const char* value, size_t length) {",
        "    for (size_t i = 0; i < COLLECTION_COUNT; ++i)",
        "        if (detail::matches(value, length, COLLECTIONS[i], false)) return true;",
        "    return false;",
        "}",
        "inline bool approvedCdnHost(const char* value, size_t length) {",
        "    for (size_t i = 0; i < CDN_HOST_COUNT; ++i)",
        "        if (detail::matches(value, length, CDN_HOSTS[i], true)) return true;",
        "    return false;",
        "}",
        "} // namespace peppyArchiveSources",
        "",
        "#endif // PEPPY_ARCHIVE_SOURCES_H",
        "",
    ])
    return "\n".join(lines)


def write_header(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", newline="\n", dir=path.parent,
                                         prefix=path.name + ".", suffix=".tmp", delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(content)
        os.replace(temporary, path)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--policy", required=True, type=Path, help="reviewed archive_sources.json")
    parser.add_argument("--output", required=True, type=Path, help="generated archive_sources.h")
    parser.add_argument("--check", action="store_true", help="fail if the existing header differs; do not write")
    args = parser.parse_args()
    try:
        if (args.policy.resolve() == args.output.resolve()
                or (args.output.exists() and os.path.samefile(args.policy, args.output))):
            raise ValueError("--output must differ from the input policy and its aliases")
        policy = load_archive_policy(args.policy)
        content = generate_archive_header(policy)
        if args.check:
            expected = content.encode("utf-8")
            with args.output.open("rb") as stream:
                actual = stream.read(len(expected) + 1)
            if actual != expected:
                raise ValueError("generated Archive header does not match the reviewed policy; regenerate it")
        else:
            write_header(args.output, content)
    except (OSError, ValueError, UnicodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(f"{'Checked' if args.check else 'Generated'} {args.output}: "
          f"{len(policy['collections'])} reviewed collections, {len(policy['cdn_hosts'])} exact CDN hosts.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
