#!/usr/bin/env python3
"""Bake antialiased text and the existing Peppy icon into a native C++ header."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import TextIO

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print(
        "error: Pillow is required to generate UI assets; install it with "
        "python3 -m pip install Pillow",
        file=sys.stderr,
    )
    raise SystemExit(1)


FONT_DIRECTORY = Path("/usr/share/fonts/truetype/dejavu")
FONT_SPECS = (
    ("FONT_SMALL", 22, "DejaVuSans.ttf"),
    ("FONT_BODY", 26, "DejaVuSans.ttf"),
    ("FONT_CARD", 28, "DejaVuSans-Bold.ttf"),
    ("FONT_TITLE", 34, "DejaVuSans-Bold.ttf"),
    ("FONT_HEADING", 42, "DejaVuSans-Bold.ttf"),
    ("FONT_HERO", 68, "DejaVuSans-Bold.ttf"),
)
PORTUGUESE_CHARACTERS = "ÀÁÂÃÄÇÈÉÊËÌÍÎÏÑÒÓÔÕÖÙÚÛÜàáâãäçèéêëìíîïñòóôõöùúûü"
CATALOG_CHARACTERS = "ŌΣ→∀"
CHARACTERS = tuple(
    sorted(set(range(32, 127)) | {ord(char) for char in PORTUGUESE_CHARACTERS + CATALOG_CHARACTERS})
)


def write_values(stream: TextIO, values, formatter, per_line: int) -> None:
    """Write bounded lines without retaining a second copy of a large array."""
    line = []
    for value in values:
        line.append(formatter(value))
        if len(line) == per_line:
            stream.write("    " + ", ".join(line) + ",\n")
            line.clear()
    if line:
        stream.write("    " + ", ".join(line) + ",\n")


def write_font(stream: TextIO, name: str, size: int, filename: str) -> None:
    font = ImageFont.truetype(str(FONT_DIRECTORY / filename), size)
    ascent, descent = font.getmetrics()
    glyphs = []
    pixels = bytearray()
    for code in CHARACTERS:
        char = chr(code)
        left, top, right, bottom = font.getbbox(char, anchor="ls")
        width, height = right - left, bottom - top
        advance = round(font.getlength(char))
        glyphs.append((code, len(pixels), width, height, advance, left, top))
        if width > 0 and height > 0:
            bitmap = Image.new("L", (width, height), 0)
            ImageDraw.Draw(bitmap).text(
                (-left, -top), char, font=font, fill=255, anchor="ls"
            )
            pixels.extend(bitmap.tobytes())

    stream.write(f"// {filename}, {size}px; alpha masks are packed by glyph.\n")
    stream.write(f"static const uint8_t {name}_pixels[] = {{\n")
    write_values(stream, pixels, lambda value: f"0x{value:02X}", 16)
    stream.write("};\n")
    stream.write(f"static const UiGlyph {name}_glyphs[] = {{\n")
    for code, offset, width, height, advance, left, top in glyphs:
        stream.write(
            f"    {{0x{code:04X}, {offset}, {width}, {height}, "
            f"{advance}, {left}, {top}}},\n"
        )
    stream.write("};\n")
    stream.write(
        f"static const UiFont {name} = {{{name}_glyphs, {name}_pixels, "
        f"{len(glyphs)}, {ascent}, {ascent + descent}}};\n\n"
    )


def generate_header(icon_path: Path, output_path: Path) -> None:
    for filename in sorted({spec[2] for spec in FONT_SPECS}):
        if not (FONT_DIRECTORY / filename).is_file():
            raise ValueError(
                f"missing font: {FONT_DIRECTORY / filename}; "
                "install the fonts-dejavu-core package"
            )
    if icon_path.resolve() == output_path.resolve():
        raise ValueError("--output must be different from --icon")
    with Image.open(icon_path) as source:
        if source.size != (512, 512):
            raise ValueError(
                f"Peppy icon must already be 512x512; got "
                f"{source.width}x{source.height}. The generator does not resize artwork."
            )
        # Preserve source color channels and coordinates; no filtering or redraw.
        icon = source.convert("RGB")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(
            "// Generated by native/scripts/generate-ui-assets.py; do not edit.\n"
            "// Build-time assets only; the PS4 runtime needs no Pillow or font files.\n"
            "#ifndef PEPPY_UI_ASSETS_H\n"
            "#define PEPPY_UI_ASSETS_H\n\n"
            "#include <stdint.h>\n\n"
            "struct UiGlyph {\n"
            "    uint32_t code, offset;\n"
            "    uint16_t width, height, advance;\n"
            "    int16_t left, top;\n"
            "};\n"
            "struct UiFont {\n"
            "    const UiGlyph* glyphs;\n"
            "    const uint8_t* pixels;\n"
            "    int count, ascent, lineHeight;\n"
            "};\n\n"
            "// Glyph left/top are relative to a left-aligned baseline.\n"
            "// For a top-aligned label, baseline = label_y + font.ascent.\n\n"
        )
        for name, size, filename in FONT_SPECS:
            write_font(stream, name, size, filename)
        stream.write(
            "// Original Peppy icon pixels in row-major RGB order.\n"
            "static const int ui_peppy_width = 512;\n"
            "static const int ui_peppy_height = 512;\n"
            "static const uint32_t ui_peppy_pixels[] = {\n"
        )
        rgb_channels = iter(icon.tobytes())
        write_values(
            stream,
            (r << 16 | g << 8 | b for r, g, b in zip(rgb_channels, rgb_channels, rgb_channels)),
            lambda value: f"0x{value:06X}",
            8,
        )
        stream.write("};\n\n#endif // PEPPY_UI_ASSETS_H\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--icon", required=True, type=Path, help="existing 512x512 Peppy icon")
    parser.add_argument("--output", required=True, type=Path, help="destination ui_assets.h")
    args = parser.parse_args()
    try:
        generate_header(args.icon, args.output)
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(f"Generated {args.output} ({args.output.stat().st_size:,} bytes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
