// Generated by native/scripts/archive_policy.py; do not edit.
// Exact reviewed collections and hosts come from native/archive_sources.json.
#ifndef PEPPY_ARCHIVE_SOURCES_H
#define PEPPY_ARCHIVE_SOURCES_H

#include <stddef.h>

namespace peppyArchiveSources {
static const char* const COLLECTIONS[] = {
    "o-bom-de-guerra-1",
    "parasite-eve-ii-pt-br",
    "ps4-fpkg-collection-english-a",
    "ps4-fpkg-collection-english-b",
    "ps4-fpkg-collection-english-c",
    "ps4-fpkg-collection-english-d",
    "ps4-fpkg-collection-english-e",
    "ps4-fpkg-collection-english-f",
    "ps4-fpkg-collection-english-g",
    "ps4-fpkg-collection-english-h",
    "ps4-fpkg-collection-english-i",
    "ps4-fpkg-collection-english-j",
    "ps4-fpkg-collection-english-k",
    "ps4-fpkg-collection-english-l",
    "ps4-fpkg-collection-english-n",
    "ps4-fpkg-collection-english-o",
    "ps4-fpkg-collection-english-p",
    "ps4-fpkg-collection-english-q",
    "ps4-fpkg-collection-english-r",
    "ps4-fpkg-collection-english-s",
    "ps4-fpkg-collection-english-t",
    "ps4-fpkg-collection-english-u",
    "ps4-fpkg-collection-english-v",
    "ps4-fpkg-collection-english-w",
    "ps4-fpkg-collection-english-x",
    "ps4-fpkg-collection-english-y",
    "ps4-fpkg-collection-english-z",
};
static const size_t COLLECTION_COUNT = sizeof(COLLECTIONS) / sizeof(COLLECTIONS[0]);
static const char* const CDN_HOSTS[] = {
    "dn710402.ca.archive.org",
    "dn710607.ca.archive.org",
    "dn720701.ca.archive.org",
    "dn720703.ca.archive.org",
    "dn720705.ca.archive.org",
    "dn720803.ca.archive.org",
    "dn721200.ca.archive.org",
    "dn721204.ca.archive.org",
    "dn721301.ca.archive.org",
    "dn721302.ca.archive.org",
    "dn721501.ca.archive.org",
    "dn721505.ca.archive.org",
    "dn721604.ca.archive.org",
    "dn721605.ca.archive.org",
    "dn721700.ca.archive.org",
    "dn721707.ca.archive.org",
    "dn721708.ca.archive.org",
    "dn721805.ca.archive.org",
    "dn721904.ca.archive.org",
    "dn721905.ca.archive.org",
    "dn721908.ca.archive.org",
    "dn760000.eu.archive.org",
    "dn760003.eu.archive.org",
    "dn760009.eu.archive.org",
    "dn760103.eu.archive.org",
    "dn760104.eu.archive.org",
    "dn760105.eu.archive.org",
    "dn760108.eu.archive.org",
    "dn760109.eu.archive.org",
    "ia600504.us.archive.org",
    "ia600704.us.archive.org",
    "ia600705.us.archive.org",
    "ia600706.us.archive.org",
    "ia600708.us.archive.org",
    "ia601004.us.archive.org",
    "ia601401.us.archive.org",
    "ia601504.us.archive.org",
    "ia601507.us.archive.org",
    "ia601509.us.archive.org",
    "ia601602.us.archive.org",
    "ia601807.us.archive.org",
    "ia601906.us.archive.org",
    "ia601907.us.archive.org",
    "ia800504.us.archive.org",
    "ia800705.us.archive.org",
    "ia800706.us.archive.org",
    "ia800708.us.archive.org",
    "ia800905.us.archive.org",
    "ia801004.us.archive.org",
    "ia801401.us.archive.org",
    "ia801507.us.archive.org",
    "ia801509.us.archive.org",
    "ia801602.us.archive.org",
    "ia801605.us.archive.org",
    "ia801807.us.archive.org",
    "ia801906.us.archive.org",
    "ia801907.us.archive.org",
};
static const size_t CDN_HOST_COUNT = sizeof(CDN_HOSTS) / sizeof(CDN_HOSTS[0]);

namespace detail {
inline char lower(char c) { return c >= 'A' && c <= 'Z' ? char(c + ('a' - 'A')) : c; }
inline bool matches(const char* value, size_t length, const char* expected, bool dns) {
    if (!value) return false;
    for (size_t i = 0; i < length; ++i) {
        if (!expected[i] || (dns ? lower(value[i]) : value[i]) != expected[i]) return false;
    }
    return !expected[length];
}
} // namespace detail

inline bool approvedCollection(const char* value, size_t length) {
    for (size_t i = 0; i < COLLECTION_COUNT; ++i)
        if (detail::matches(value, length, COLLECTIONS[i], false)) return true;
    return false;
}
inline bool approvedCdnHost(const char* value, size_t length) {
    for (size_t i = 0; i < CDN_HOST_COUNT; ++i)
        if (detail::matches(value, length, CDN_HOSTS[i], true)) return true;
    return false;
}
} // namespace peppyArchiveSources

#endif // PEPPY_ARCHIVE_SOURCES_H
